services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: innovachain-backend
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  data-volume:
