services:
  backend:
    build:
      context: ./Innovachain_backend/innovchain_backend
      dockerfile: Dockerfile
    image: innovachain-backend
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

  midjourney:
    build:
      context: ./midjourney-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

volumes:
  data-volume:
