"""add last_executions table

Revision ID: 0ca35dfc8853
Revises: 1af6f0a5bb30
Create Date: 2024-10-28 01:36:47.656680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca35dfc8853'
down_revision: Union[str, None] = '1af6f0a5bb30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_executions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('last_execution_time', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # Set the default value for last_execution_time using raw SQL for SQLite
    op.execute("UPDATE last_executions SET last_execution_time='1970-01-01 00:00:00' WHERE last_execution_time IS NULL;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_executions')
    # ### end Alembic commands ###
