"""add reference and like count in images table

Revision ID: 18a6cc4f50f4
Revises: 1dc4f9e86629
Create Date: 2024-10-26 12:15:49.810889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a6cc4f50f4'
down_revision: Union[str, None] = '1dc4f9e86629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('reference_count', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'like_count')
    op.drop_column('images', 'reference_count')
    # ### end Alembic commands ###
