"""Add reward field to Image model and total_rewards field to UserStats model

Revision ID: 1af6f0a5bb30
Revises: b09393864813
Create Date: 2024-10-27 10:35:49.405983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af6f0a5bb30'
down_revision: Union[str, None] = 'b09393864813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('reward', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('user_stats', sa.Column('total_rewards', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'total_rewards')
    op.drop_column('images', 'reward')
    # ### end Alembic commands ###
