"""Add foreign key to Image model

Revision ID: 1dc4f9e86629
Revises: 59bc94ea36a7
Create Date: 2024-10-09 23:55:10.611387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc4f9e86629'
down_revision: Union[str, None] = '59bc94ea36a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_images_user_id_users'), 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_images_user_id_users'), type_='foreignkey')
    # ### end Alembic commands ###
