"""add is_active column

Revision ID: 59bc94ea36a7
Revises: dd9374762131
Create Date: 2024-10-05 14:05:02.631485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59bc94ea36a7'
down_revision: Union[str, None] = 'dd9374762131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'is_active')
    # ### end Alembic commands ###
